name: Eye CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4.0.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.8.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx blueprint build --all

    - name: Test
      run: npx blueprint test
